### PR TITLE
Some changes to Pong

### PR DESCRIPTION
**Pull request by magiczocker10**
…rmance on old 3DS

### CODE REVIEW

**Comment by Wolfyxon** [comment]
One issue. The enemy must go back to the original position when a round starts.

**Comment by magiczocker10** [comment]
Strange issue. It even doesn't go back in the current version.

**Comment by magiczocker10** [comment]
Should be fixed now

**Comment by Wolfyxon** [comment]
> Strange issue. It even doesn't go back in the current version.

I guess I haven't noticed. All good

**Pull request merged**
