### PR TITLE
Some MineSweeper changes

### LINKED ISSUE #75: [Minesweeper] Flags should equal to the number of bombs on the board
I should not be able to do this.
image

### PR DESCRIPTION
**Pull request by magiczocker10**
* Fix #75
* Change updateTime function
* Flagged cells can't be opened automatically

### CODE REVIEW

**Comment by Wolfyxon** [comment]
> Flagged cells can't be opened automatically

Is that how it works in the original?

**Comment by magiczocker10** [comment]
> Is that how it works in the original?
Yes

**Comment by magiczocker10** [comment]
I tested it on my windows xp virtual machine

**Comment by Wolfyxon** [comment]
Alright then

**Pull request merged**
