### PR TITLE
Add new barcode features

### PR DESCRIPTION
**Pull request by basic-experimental**
This modifies the qr code generator to also be able to generate other codes. Aztec, Codabar, Code39, Code128, Data Matrix, EAN-8, EAN-13, PDF-417, UPC-A, and UPC-E are now supported. This was done by switching the API over to [BarcodeAPI.org](url). The name of the app was changed to reflect the new functionality. I have tested on a new 3DS. I am unable to test this change on a DSI, so I do not know if it works on there or not. I have left the marker indicating it as compatible for now.

### CODE REVIEW

**Comment by magiczocker10** [comment]
I tested your change on new 3DS, old 3DS and DSi. Non of them could load the image with a local webserver or a [test github page](https://github.com/magiczocker10/test).

**Comment by magiczocker10** [comment]
Error I receive via new 3DS developer tools.

image

**Comment by Wolfyxon** [comment]
Try HTTP. The 3DS certificates are pretty old so some websites won't accept them.

**Comment by magiczocker10** [comment]
http removes the certificate error, but the request keeps failing

**Comment by basic-experimental** [comment]
Although it appeared to work every time I tested it yesterday, it appears that it does not work all the time. If it is able to make one successful request after the page loads, it seems to be able to do so again. If it is not able to make a successful request, it will not be able to do so again. This seems to persist until the page is refreshed, then it seems to be randomized again whether or not it will work. Opening one of the API request URLs directly in the address bar works every time. I'm not sure what would cause this. Here are some screenshots from Luma3DS of it working: 
2024-06-01_06-07-52 669_top
2024-06-01_06-07-52 669_bot
To open the menu to take a screenshot, I had to use L & R, so it's taken while it's transitioning pages.

**Comment by magiczocker10** [comment]
Can you open the developer tools and provide errors from the console? You can open them by holding X and Y on browser loading screen.

**Comment by basic-experimental** [comment]
It’s the same error you’re getting about CA certificates.

**Comment by basic-experimental** [comment]
It should be ready to test again. I have it working consistently on my 3DS now.

**Comment by magiczocker10** [comment]
Tested it on old 3DS, but looks like it doesn't support "FileReader" constructor.

Could you adopt this design? It looks way better than your list view.
https://github.com/magiczocker10/test

**Comment by magiczocker10** [comment]
From my testing, you can directly use `qr.src = imageUrl` without XMLHttpRequest.

**Comment by basic-experimental** [comment]
> Tested it on old 3DS, but looks like it doesn't support "FileReader" constructor.
> 
> Could you adopt this design? It looks way better than your list view. https://github.com/magiczocker10/test

Sure, that looks good. I’ll use that design.


> From my testing, you can directly use `qr.src = imageUrl` without XMLHttpRequest. This works on old and new 3DS.
> 
> Edit: Also works on DSi.

I never tested whether this worked or not after implementing the new API. That’s good, I’ll change that too.

**Comment by basic-experimental** [comment]
This should be ready again.

**Comment by magiczocker10** [comment]
Thank you. I'll fix css compability issues with old 3DS and DSi after this PR was merged.

**Comment by Wolfyxon** [comment]
Looks good, but why are the initial images GIFs instead of PNGs?

**Comment by basic-experimental** [comment]
At least in this case, GIFs compress a little better than PNGs (~half a kilobyte vs ~a kilobyte). I thought it may help with RAM usage, and not fill up the cache quite as much. But I know the actual gains from this are quite minor, so if you want me to swap them with PNGs, I can do that.

**Comment by Wolfyxon** [comment]
I've noticed a few small issues, but I can fix them myself.
Otherwise everything looks good. 

Thanks.

**Pull request merged**
